/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./constants/**/*.{js,jsx,ts,tsx}",
    "./context/**/*.{js,jsx,ts,tsx}",
    "./hooks/**/*.{js,jsx,ts,tsx}",
    "./utils/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#8A77F4",
        secondary: "#8b62f3",
        accent: "#BEE3DB",
        surface: "#FAF9F9",
        textPrimary: "#1E1F45",
        whitePrimary: "#FFFFFF",
        description: "#6F6D6D",
        muted: "#94A3B8",
        blackPrimary: "#1E1F45",
        danger: "#B42318",
        dangerSurface: "#FEF3F2",
        success: "#0F6B55",
        successSurface: "#BEE3DB",
        warning: "#805000",
        warningSurface: "#FFF6DD",
        turnover: "#B7791F",
        info: "#2563EB",
        infoSurface: "#EFF6FF",
      },
      fontSize: {
        font10: ["10px", { lineHeight: "14px" }],
        font14: ["14px", { lineHeight: "20px" }],
        font24: ["24px", { lineHeight: "32px" }],
      },
      fontFamily: {
        raleway: ["Raleway_400Regular"],
        ralewayMedium: ["Raleway_500Medium"],
        ralewaySemiBold: ["Raleway_600SemiBold"],
        ralewayBold: ["Raleway_700Bold"],
        ralewayExtraBold: ["Raleway_800ExtraBold"],
        ralewayBlack: ["Raleway_900Black"],
      },
    },
  },
  plugins: [],
};
