/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./constants/**/*.{js,jsx,ts,tsx}",
    "./context/**/*.{js,jsx,ts,tsx}",
    "./hooks/**/*.{js,jsx,ts,tsx}",
    "./utils/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        secondary: "rgb(var(--color-secondary) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        textPrimary: "rgb(var(--color-text) / <alpha-value>)",
        panel: "rgb(var(--color-panel) / <alpha-value>)",
        whitePrimary: "#FFFFFF",
        description: "rgb(var(--color-description) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        blackPrimary: "rgb(var(--color-text) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        dangerSurface: "rgb(var(--color-danger-surface) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        successSurface: "rgb(var(--color-success-surface) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        warningSurface: "rgb(var(--color-warning-surface) / <alpha-value>)",
        turnover: "rgb(var(--color-turnover) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        infoSurface: "rgb(var(--color-info-surface) / <alpha-value>)",
      },
      fontSize: {
        font10: ["10px", { lineHeight: "14px" }],
        font14: ["14px", { lineHeight: "20px" }],
        font24: ["24px", { lineHeight: "32px" }],
      },
      fontFamily: {
        raleway: ["Raleway_400Regular"],
        ralewayMedium: ["Raleway_500Medium"],
        ralewaySemiBold: ["Raleway_600SemiBold"],
        ralewayBold: ["Raleway_700Bold"],
        ralewayExtraBold: ["Raleway_800ExtraBold"],
        ralewayBlack: ["Raleway_900Black"],
      },
    },
  },
  plugins: [],
};
